[Interface]
Role = exit
Mode = l3
EncryptionKeyFile = secret.txt
SessionContext = multibond-v01

Bond = true
BondMax = 256
BondActive = 196
BondMinActive = 4
BondPreferredRTT = 120ms
BondMaxRTT = 150ms
BondEmergencyRTT = 300ms
BondRTTSpread = 30ms

[Transport "volga-01"]
Type = vyandex
Priority = 50
URL = YOUR_VOLGA_DOCUMENT_01

[Transport "volga-02"]
Type = vyandex
Priority = 50
URL = YOUR_VOLGA_DOCUMENT_02

[Transport "mail-01"]
Type = mailru
Priority = 50
URL = YOUR_MAILRU_DOCUMENT

[Transport "max-01"]
Type = oneme
Priority = 50
Token = YOUR_MAX_TOKEN
UID = YOUR_MAX_UID
